services:
  postgis:
    image: postgis/postgis
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: postgis
    environment:
      - POSTGRES_DB=tkgqa
      - POSTGRES_USER=tkgqa
      - POSTGRES_PASSWORD=tkgqa
    platform: linux/amd64
    ports:
      - "5433:5432"
    volumes:
      - tkgqa_generator_postgis_data:/var/lib/postgresql/data

volumes:
  tkgqa_generator_postgis_data:
    external: true
