site_name: EventTimelineQA

theme:
  name: material
  logo: imgs/AI4WA.png
  favicon: imgs/favicon.ico
  features:
    - search.suggest
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - encryptcontent:
      global_password: 'TimelineKGQA'
  - gen-files:
      scripts:
        - script/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            show_source_link: true

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.extra