site_name: TimelineKGQA

theme:
  name: material
  features:
    - search.suggest
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - gen-files:
      scripts:
        - script/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            show_source_link: true

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.extra