site_name: TimelineQA

theme:
  name: material
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            show_source_link: true