site_name: TimelineQA

theme:
  name: material
plugins:
  - search
  - encryptcontent:
      global_password: 'TimelineQA'
  - gen-files:
      scripts:
        - script/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            show_source_link: true

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.extra